void test_74253(void)
    {   
        sym[1]=3;
        sym[2]=5;
        sym[3]=2;
        res=0;
        sym[0]=12;
        Direct_L=191;
        Direct_H=127;
        Port_L=40;
        Port_H=41;
        delay_ms(1);
        if ((Pin_L==104) && (Pin_H==41)) res=1;
            else res=0;
        Port_L=40;
        Port_H=45;
        delay_ms(1);
        if ((Pin_L==40) && (Pin_H==173) && (res==1)) res=1;
            else res=0;             
        Port_L=42;
        Port_H=41;
        delay_ms(1);
        if ((Pin_L==106) && (Pin_H==41) && (res==1)) res=1;
            else res=0;
        Port_L=42;
        Port_H=45;
        delay_ms(1);
        if ((Pin_L==42) && (Pin_H==173) && (res==1)) res=1;
            else res=0;
        Port_L=20;
        Port_H=81;
        delay_ms(1);
        if ((Pin_L==20) && (Pin_H==209) && (res==1)) res=1;
            else res=0;
        Port_L=20;
        Port_H=85;
        delay_ms(1);
        if ((Pin_L==84) && (Pin_H==85) && (res==1)) res=1;
            else res=0; 
        Port_L=22;
        Port_H=81;
        delay_ms(1);
        if ((Pin_L==22) && (Pin_H==209) && (res==1)) res=1;
            else res=0;
        Port_L=22;
        Port_H=85;
        delay_ms(1);
        if ((Pin_L==86) && (Pin_H==85) && (res==1)) res=1;
            else res=0;             
        if (res==1) sym[0]=10;
            else sym[0]=11;
        Port_L=0;
        Port_H=0;                                        
    }