void test_74295(void)
    {
        sym[1]=5;
        sym[2]=9;
        sym[3]=2;
        res=0;
        sym[0]=12;
        Direct_L=255;
        Direct_H=225;
        Port_L=32;
        Port_H=97;
        Port_H=65;
        Port_H=97;
        Port_L=0;
        delay_ms(1);
        if ((Pin_L==0) && (Pin_H==97)) res=1;
            else res=0;
        Port_L=1;
        Port_H=65;
        Port_H=97;
        if ((Pin_L==1) && (Pin_H==99) && (res==1)) res=1;
            else res=0;
        Port_H=65;
        Port_H=97;
        Port_H=65;
        Port_H=97;
        Port_H=65;
        Port_H=97;
        if ((Pin_L==1) && (Pin_H==127) && (res==1)) res=1;
            else res=0;
        Port_L=32;
        Port_H=65;
        Port_H=97;
        Port_L=0;
        delay_ms(1);
        if ((Pin_L==0) && (Pin_H==97) && (res==1)) res=1;
            else res=0;                    
        if (res==1) sym[0]=10;
            else sym[0]=11;   
        Port_L=0;
        Port_H=0;            
    }