void test_74138(void)
    {   
        sym[1]=8;
        sym[2]=3;
        sym[3]=1;
        res=0;
        sym[0]=12;
        Direct_L=191;
        Direct_H=1;
        Port_L=32;
        Port_H=1;
        delay_ms(1);
        if ((Pin_L==96) && (Pin_H==253)) res=1;
            else res=0;
        Port_L=33;
        Port_H=1;
        delay_ms(1);
        if ((Pin_L==97) && (Pin_H==251) && (res==1)) res=1;
            else res=0;
        Port_L=34;
        delay_ms(1);
        if ((Pin_L==98) && (Pin_H==247) && (res==1)) res=1;
            else res=0;
        Port_L=35;
        delay_ms(1);
        if ((Pin_L==99) && (Pin_H==239) && (res==1)) res=1;
            else res=0;
        Port_L=36;
        delay_ms(1);
        if ((Pin_L==100) && (Pin_H==223) && (res==1)) res=1;
            else res=0;
        Port_L=37;
        delay_ms(1);
        if ((Pin_L==101) && (Pin_H==191) && (res==1)) res=1;
            else res=0;
        Port_L=38;
        delay_ms(1);
        if ((Pin_L==102) && (Pin_H==127) && (res==1)) res=1;
            else res=0; 
        Port_L=39;
        delay_ms(1);
        if ((Pin_L==39) && (Pin_H==255) && (res==1)) res=1;
            else res=0;                               
        if (res==1) sym[0]=10;
            else sym[0]=11;
        Port_L=0;
        Port_H=0;                                        
    }